FROM debian:latest

RUN apt-get update -y;

RUN apt-get upgrade -y;

RUN apt-get install -y build-essential;

RUN apt-get install -y automake autoconf;

RUN apt-get install -y python3 python3-pip python3-venv python3-django python3-numpy;

RUN apt-get install -y vim vim-doc vim-scripts universal-ctags;

RUN apt-get install sqlite3 -y;

WORKDIR /var/www/html/

COPY . .

EXPOSE 8000
