# Generated by Django 5.1 on 2024-09-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="skills",
            new_name="skill",
        ),
    ]
